### ISSUE TITLE
皮肤组件 skin_set_item_label  无效果，  InitMiniGUIExt  已经没有了， 代替者是什么？

### ISSUE THREAD

**Issue by maikebing** [VincentWei/mgutils#1]
我使用了皮肤组件， 通过 skin_set_item_label   切换图片， 但是 目前图片不显示，不知道是不是因为 InitMiniGUIExt   和  MiniGUIExtCleanUp 在 5.0 里不存在的原因？

**Comment by VincentWei** [comment]
This should have nothing to do with `InitMiniGUIExt` and `MiniGUIExCleanup` functions.

You need to load the bitmaps by yourself before calling `skin_init` function. Please see `skindemo.c` in mGUtils in `samples/skin` directory.

If the demo can not work correctly, please back here.
